In [27]:
import pandas as pd
import numpy as np
import matplotlib as plt
import glob, os

DATA = '../NY-Citibike-data-science-case-study/data_citibike/'

In [28]:
# df = pd.concat(map(pd.read_csv, glob.glob(os.path.join('', "data_citibike*.csv"))))


all_files = glob.glob(DATA + "/*.csv")

# # li = []

# # for filename in all_files:
# #     df = pd.read_csv(filename, index_col=None, header=0)
# #     li.append(df)

# frame = pd.concat(li, axis=0, ignore_index=True)

df = pd.concat((pd.read_csv(f) for f in all_files))

In [31]:
df.head()

,tripduration,starttime,stoptime,start station id,start station name,start station latitude,start station longitude,end station id,end station name,end station latitude,end station longitude,bikeid,usertype,birth year,gender
0,134,2018-02-01 07:38:15.8650,2018-02-01 07:40:30.5820,3183,Exchange Place,40.716247,-74.033459,3184,Paulus Hook,40.714145,-74.033552,29615,Subscriber,1966,1
1,413,2018-02-01 08:19:35.8160,2018-02-01 08:26:29.6490,3183,Exchange Place,40.716247,-74.033459,3267,Morris Canal,40.712419,-74.038526,29641,Subscriber,1986,2
2,77,2018-02-01 08:31:03.0860,2018-02-01 08:32:20.3510,3183,Exchange Place,40.716247,-74.033459,3184,Paulus Hook,40.714145,-74.033552,29621,Subscriber,1975,1
3,404,2018-02-01 15:23:15.0850,2018-02-01 15:29:59.9300,3183,Exchange Place,40.716247,-74.033459,3267,Morris Canal,40.712419,-74.038526,31934,Subscriber,1980,1
4,230,2018-02-01 15:26:01.8240,2018-02-01 15:29:52.5440,3183,Exchange Place,40.716247,-74.033459,3213,Van Vorst Park,40.718489,-74.047727,29642,Subscriber,1986,1

In [39]:
df['tripduration'] = df['tripduration']/60

{'Customer', 'Subscriber'}